// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: lancet/v1/lancet.proto

package lancetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LancetService_Ping_FullMethodName               = "/lancet.v1.LancetService/Ping"
	LancetService_IngestDocument_FullMethodName     = "/lancet.v1.LancetService/IngestDocument"
	LancetService_GetIngestionStatus_FullMethodName = "/lancet.v1.LancetService/GetIngestionStatus"
	LancetService_QueryRAG_FullMethodName           = "/lancet.v1.LancetService/QueryRAG"
	LancetService_QueryGraph_FullMethodName         = "/lancet.v1.LancetService/QueryGraph"
)

// LancetServiceClient is the client API for LancetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LancetServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	IngestDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestDocumentRequest, IngestDocumentResponse], error)
	GetIngestionStatus(ctx context.Context, in *GetIngestionStatusRequest, opts ...grpc.CallOption) (*GetIngestionStatusResponse, error)
	QueryRAG(ctx context.Context, in *QueryRAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error)
	QueryGraph(ctx context.Context, in *QueryGraphRequest, opts ...grpc.CallOption) (*QueryGraphResponse, error)
}

type lancetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLancetServiceClient(cc grpc.ClientConnInterface) LancetServiceClient {
	return &lancetServiceClient{cc}
}

func (c *lancetServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LancetService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lancetServiceClient) IngestDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestDocumentRequest, IngestDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LancetService_ServiceDesc.Streams[0], LancetService_IngestDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestDocumentRequest, IngestDocumentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LancetService_IngestDocumentClient = grpc.ClientStreamingClient[IngestDocumentRequest, IngestDocumentResponse]

func (c *lancetServiceClient) GetIngestionStatus(ctx context.Context, in *GetIngestionStatusRequest, opts ...grpc.CallOption) (*GetIngestionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngestionStatusResponse)
	err := c.cc.Invoke(ctx, LancetService_GetIngestionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lancetServiceClient) QueryRAG(ctx context.Context, in *QueryRAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LancetService_ServiceDesc.Streams[1], LancetService_QueryRAG_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRAGRequest, WorkflowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LancetService_QueryRAGClient = grpc.ServerStreamingClient[WorkflowEvent]

func (c *lancetServiceClient) QueryGraph(ctx context.Context, in *QueryGraphRequest, opts ...grpc.CallOption) (*QueryGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGraphResponse)
	err := c.cc.Invoke(ctx, LancetService_QueryGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LancetServiceServer is the server API for LancetService service.
// All implementations must embed UnimplementedLancetServiceServer
// for forward compatibility.
type LancetServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	IngestDocument(grpc.ClientStreamingServer[IngestDocumentRequest, IngestDocumentResponse]) error
	GetIngestionStatus(context.Context, *GetIngestionStatusRequest) (*GetIngestionStatusResponse, error)
	QueryRAG(*QueryRAGRequest, grpc.ServerStreamingServer[WorkflowEvent]) error
	QueryGraph(context.Context, *QueryGraphRequest) (*QueryGraphResponse, error)
	mustEmbedUnimplementedLancetServiceServer()
}

// UnimplementedLancetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLancetServiceServer struct{}

func (UnimplementedLancetServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLancetServiceServer) IngestDocument(grpc.ClientStreamingServer[IngestDocumentRequest, IngestDocumentResponse]) error {
	return status.Errorf(codes.Unimplemented, "method IngestDocument not implemented")
}
func (UnimplementedLancetServiceServer) GetIngestionStatus(context.Context, *GetIngestionStatusRequest) (*GetIngestionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIngestionStatus not implemented")
}
func (UnimplementedLancetServiceServer) QueryRAG(*QueryRAGRequest, grpc.ServerStreamingServer[WorkflowEvent]) error {
	return status.Errorf(codes.Unimplemented, "method QueryRAG not implemented")
}
func (UnimplementedLancetServiceServer) QueryGraph(context.Context, *QueryGraphRequest) (*QueryGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryGraph not implemented")
}
func (UnimplementedLancetServiceServer) mustEmbedUnimplementedLancetServiceServer() {}
func (UnimplementedLancetServiceServer) testEmbeddedByValue()                       {}

// UnsafeLancetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LancetServiceServer will
// result in compilation errors.
type UnsafeLancetServiceServer interface {
	mustEmbedUnimplementedLancetServiceServer()
}

func RegisterLancetServiceServer(s grpc.ServiceRegistrar, srv LancetServiceServer) {
	// If the following call pancis, it indicates UnimplementedLancetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LancetService_ServiceDesc, srv)
}

func _LancetService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LancetServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LancetService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LancetServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LancetService_IngestDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LancetServiceServer).IngestDocument(&grpc.GenericServerStream[IngestDocumentRequest, IngestDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LancetService_IngestDocumentServer = grpc.ClientStreamingServer[IngestDocumentRequest, IngestDocumentResponse]

func _LancetService_GetIngestionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngestionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LancetServiceServer).GetIngestionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LancetService_GetIngestionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LancetServiceServer).GetIngestionStatus(ctx, req.(*GetIngestionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LancetService_QueryRAG_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRAGRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LancetServiceServer).QueryRAG(m, &grpc.GenericServerStream[QueryRAGRequest, WorkflowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LancetService_QueryRAGServer = grpc.ServerStreamingServer[WorkflowEvent]

func _LancetService_QueryGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LancetServiceServer).QueryGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LancetService_QueryGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LancetServiceServer).QueryGraph(ctx, req.(*QueryGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LancetService_ServiceDesc is the grpc.ServiceDesc for LancetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LancetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lancet.v1.LancetService",
	HandlerType: (*LancetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LancetService_Ping_Handler,
		},
		{
			MethodName: "GetIngestionStatus",
			Handler:    _LancetService_GetIngestionStatus_Handler,
		},
		{
			MethodName: "QueryGraph",
			Handler:    _LancetService_QueryGraph_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestDocument",
			Handler:       _LancetService_IngestDocument_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "QueryRAG",
			Handler:       _LancetService_QueryRAG_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lancet/v1/lancet.proto",
}
