// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID            string
	Filename      string
	FileSize      int64
	Status        string
	ChunkCount    int32
	ErrorMessage  pgtype.Text
	ChunkStrategy string
	ChunkSize     int32
	ChunkOverlap  int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamp
}
