// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueReconciliationIntents = `-- name: ClaimDueReconciliationIntents :many
WITH due AS (
  SELECT document_id
  FROM document_reconciliation_intents
  WHERE next_attempt_at <= CURRENT_TIMESTAMP
  ORDER BY next_attempt_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE document_reconciliation_intents dri
SET
  next_attempt_at = $2,
  updated_at = CURRENT_TIMESTAMP
FROM due
WHERE dri.document_id = due.document_id
RETURNING dri.document_id, dri.desired_status, dri.reason_class, dri.retry_count, dri.next_attempt_at, dri.last_error_class, dri.created_at, dri.updated_at
`

type ClaimDueReconciliationIntentsParams struct {
	Limit         int32
	NextAttemptAt pgtype.Timestamp
}

func (q *Queries) ClaimDueReconciliationIntents(ctx context.Context, arg ClaimDueReconciliationIntentsParams) ([]DocumentReconciliationIntent, error) {
	rows, err := q.db.Query(ctx, claimDueReconciliationIntents, arg.Limit, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentReconciliationIntent
	for rows.Next() {
		var i DocumentReconciliationIntent
		if err := rows.Scan(
			&i.DocumentID,
			&i.DesiredStatus,
			&i.ReasonClass,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.LastErrorClass,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReconciliationIntent = `-- name: CreateReconciliationIntent :one
INSERT INTO document_reconciliation_intents (
  document_id,
  desired_status,
  reason_class,
  retry_count,
  next_attempt_at,
  last_error_class,
  created_at,
  updated_at
)
SELECT
  d.id,
  $2,
  $3,
  0,
  CURRENT_TIMESTAMP,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM documents d
WHERE d.id = $1 AND d.status = 'queued'
ON CONFLICT (document_id) DO UPDATE
SET
  desired_status = EXCLUDED.desired_status,
  reason_class = EXCLUDED.reason_class,
  updated_at = CURRENT_TIMESTAMP
RETURNING document_id, desired_status, reason_class, retry_count, next_attempt_at, last_error_class, created_at, updated_at
`

type CreateReconciliationIntentParams struct {
	ID            string
	DesiredStatus string
	ReasonClass   string
}

func (q *Queries) CreateReconciliationIntent(ctx context.Context, arg CreateReconciliationIntentParams) (DocumentReconciliationIntent, error) {
	row := q.db.QueryRow(ctx, createReconciliationIntent, arg.ID, arg.DesiredStatus, arg.ReasonClass)
	var i DocumentReconciliationIntent
	err := row.Scan(
		&i.DocumentID,
		&i.DesiredStatus,
		&i.ReasonClass,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username)
VALUES ($1)
RETURNING id, username, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const deleteReconciliationIntent = `-- name: DeleteReconciliationIntent :execresult
DELETE FROM document_reconciliation_intents dri
USING documents d
WHERE dri.document_id = d.id
  AND dri.document_id = $1
  AND d.status IN ('completed', 'failed')
`

func (q *Queries) DeleteReconciliationIntent(ctx context.Context, documentID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteReconciliationIntent, documentID)
}

const getDocument = `-- name: GetDocument :one
SELECT id, filename, file_size, status, chunk_count, error_message, chunk_strategy, chunk_size, chunk_overlap, created_at, updated_at FROM documents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.FileSize,
		&i.Status,
		&i.ChunkCount,
		&i.ErrorMessage,
		&i.ChunkStrategy,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReconciliationIntent = `-- name: GetReconciliationIntent :one
SELECT document_id, desired_status, reason_class, retry_count, next_attempt_at, last_error_class, created_at, updated_at FROM document_reconciliation_intents
WHERE document_id = $1
LIMIT 1
`

func (q *Queries) GetReconciliationIntent(ctx context.Context, documentID string) (DocumentReconciliationIntent, error) {
	row := q.db.QueryRow(ctx, getReconciliationIntent, documentID)
	var i DocumentReconciliationIntent
	err := row.Scan(
		&i.DocumentID,
		&i.DesiredStatus,
		&i.ReasonClass,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (
  id,
  filename,
  file_size,
  status,
  chunk_count,
  chunk_strategy,
  chunk_size,
  chunk_overlap
) VALUES (
  $1,
  $2,
  $3,
  'queued',
  0,
  $4,
  $5,
  $6
)
RETURNING id, filename, file_size, status, chunk_count, error_message, chunk_strategy, chunk_size, chunk_overlap, created_at, updated_at
`

type InsertDocumentParams struct {
	ID            string
	Filename      string
	FileSize      int64
	ChunkStrategy string
	ChunkSize     int32
	ChunkOverlap  int32
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.Filename,
		arg.FileSize,
		arg.ChunkStrategy,
		arg.ChunkSize,
		arg.ChunkOverlap,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.FileSize,
		&i.Status,
		&i.ChunkCount,
		&i.ErrorMessage,
		&i.ChunkStrategy,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkflowCheckpoint = `-- name: InsertWorkflowCheckpoint :one
INSERT INTO workflow_checkpoints (
  id,
  trace_id,
  sequence_ordinal,
  node_name,
  context_snapshot,
  created_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, trace_id, sequence_ordinal, node_name, context_snapshot, created_at
`

type InsertWorkflowCheckpointParams struct {
	ID              string
	TraceID         string
	SequenceOrdinal int32
	NodeName        string
	ContextSnapshot []byte
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) InsertWorkflowCheckpoint(ctx context.Context, arg InsertWorkflowCheckpointParams) (WorkflowCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertWorkflowCheckpoint,
		arg.ID,
		arg.TraceID,
		arg.SequenceOrdinal,
		arg.NodeName,
		arg.ContextSnapshot,
		arg.CreatedAt,
	)
	var i WorkflowCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SequenceOrdinal,
		&i.NodeName,
		&i.ContextSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const rescheduleReconciliationIntent = `-- name: RescheduleReconciliationIntent :one
UPDATE document_reconciliation_intents
SET
  retry_count = retry_count + 1,
  next_attempt_at = $2,
  last_error_class = $3,
  updated_at = CURRENT_TIMESTAMP
WHERE document_id = $1
RETURNING document_id, desired_status, reason_class, retry_count, next_attempt_at, last_error_class, created_at, updated_at
`

type RescheduleReconciliationIntentParams struct {
	DocumentID     string
	NextAttemptAt  pgtype.Timestamp
	LastErrorClass pgtype.Text
}

func (q *Queries) RescheduleReconciliationIntent(ctx context.Context, arg RescheduleReconciliationIntentParams) (DocumentReconciliationIntent, error) {
	row := q.db.QueryRow(ctx, rescheduleReconciliationIntent, arg.DocumentID, arg.NextAttemptAt, arg.LastErrorClass)
	var i DocumentReconciliationIntent
	err := row.Scan(
		&i.DocumentID,
		&i.DesiredStatus,
		&i.ReasonClass,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET
  status = $2,
  chunk_count = $3,
  error_message = $4,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status IN ('queued', 'processing')
RETURNING id, filename, file_size, status, chunk_count, error_message, chunk_strategy, chunk_size, chunk_overlap, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	ID           string
	Status       string
	ChunkCount   int32
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus,
		arg.ID,
		arg.Status,
		arg.ChunkCount,
		arg.ErrorMessage,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.FileSize,
		&i.Status,
		&i.ChunkCount,
		&i.ErrorMessage,
		&i.ChunkStrategy,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
