// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestDocumentRequest {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub chunk_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(map="string, string", tag="4")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestDocumentResponse {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub success: bool,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIngestionStatusRequest {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIngestionStatusResponse {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub chunk_count: i32,
    #[prost(string, tag="4")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DocumentFilter {
    #[prost(string, repeated, tag="1")]
    pub document_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="2")]
    pub content_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryRagRequest {
    #[prost(string, tag="1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub filter: ::core::option::Option<DocumentFilter>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Notice {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="NoticeSeverity", tag="3")]
    pub severity: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructuredCitation {
    #[prost(string, tag="1")]
    pub chunk_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub section_path: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub excerpt: ::prost::alloc::string::String,
    #[prost(bool, tag="6")]
    pub is_truncated: bool,
    #[prost(double, tag="7")]
    pub score: f64,
    #[prost(int32, tag="8")]
    pub rank: i32,
    #[prost(string, tag="9")]
    pub content_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetrievalSnapshot {
    #[prost(string, tag="1")]
    pub index_generation: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub embedding_model: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub vector_weight: f64,
    #[prost(double, tag="4")]
    pub bm25_weight: f64,
    #[prost(int32, tag="5")]
    pub rrf_k: i32,
    #[prost(int32, tag="6")]
    pub candidate_limit: i32,
    #[prost(int32, tag="7")]
    pub final_limit: i32,
    #[prost(message, optional, tag="8")]
    pub active_filter: ::core::option::Option<DocumentFilter>,
    #[prost(string, tag="9")]
    pub result_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub variant_count: u32,
    #[prost(string, repeated, tag="11")]
    pub variant_identities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRagResponse {
    #[prost(string, tag="1")]
    pub answer: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub citations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(enumeration="AnswerBasis", tag="4")]
    pub answer_basis: i32,
    #[prost(message, repeated, tag="5")]
    pub structured_citations: ::prost::alloc::vec::Vec<StructuredCitation>,
    #[prost(message, repeated, tag="6")]
    pub notices: ::prost::alloc::vec::Vec<Notice>,
    #[prost(message, optional, tag="7")]
    pub snapshot: ::core::option::Option<RetrievalSnapshot>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryGraphRequest {
    #[prost(string, tag="1")]
    pub seed_entity_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub seed_entity_name: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub hop_depth: u32,
    #[prost(string, tag="4")]
    pub relation_type_filter: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryGraphNode {
    #[prost(string, tag="1")]
    pub entity_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub entity_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryGraphEdge {
    #[prost(string, tag="1")]
    pub source_entity_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub target_entity_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub relation_type: ::prost::alloc::string::String,
    #[prost(float, tag="4")]
    pub weight: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryGraphResponse {
    #[prost(message, repeated, tag="1")]
    pub nodes: ::prost::alloc::vec::Vec<QueryGraphNode>,
    #[prost(message, repeated, tag="2")]
    pub edges: ::prost::alloc::vec::Vec<QueryGraphEdge>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeStartedEvent {
    #[prost(string, tag="1")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub inputs_summary: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeCompletedEvent {
    #[prost(string, tag="1")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub outputs_summary: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub duration_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeFailedEvent {
    #[prost(string, tag="1")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(enumeration="NodeErrorKind", tag="2")]
    pub category: i32,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub retryable: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnswerChunkEvent {
    #[prost(string, tag="1")]
    pub chunk: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub is_final: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinalAnswerEvent {
    #[prost(message, optional, tag="1")]
    pub response: ::core::option::Option<QueryRagResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckpointEvent {
    #[prost(string, tag="1")]
    pub checkpoint_type: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub sequence_ordinal: u64,
    #[prost(string, tag="3")]
    pub context_snapshot: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkflowCompletedEvent {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(int64, tag="2")]
    pub duration_ms: i64,
    #[prost(enumeration="NodeErrorKind", tag="3")]
    pub error_kind: i32,
    #[prost(string, tag="4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub final_response: ::core::option::Option<QueryRagResponse>,
    #[prost(message, repeated, tag="6")]
    pub notices: ::prost::alloc::vec::Vec<Notice>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkflowEvent {
    #[prost(string, tag="1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub sequence_ordinal: u64,
    #[prost(int64, tag="4")]
    pub timestamp_ms: i64,
    #[prost(oneof="workflow_event::Event", tags="5, 6, 7, 8, 9, 10, 11")]
    pub event: ::core::option::Option<workflow_event::Event>,
}
/// Nested message and enum types in `WorkflowEvent`.
pub mod workflow_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="5")]
        NodeStarted(super::NodeStartedEvent),
        #[prost(message, tag="6")]
        NodeCompleted(super::NodeCompletedEvent),
        #[prost(message, tag="7")]
        NodeFailed(super::NodeFailedEvent),
        #[prost(message, tag="8")]
        AnswerChunk(super::AnswerChunkEvent),
        #[prost(message, tag="9")]
        FinalAnswer(super::FinalAnswerEvent),
        #[prost(message, tag="10")]
        Checkpoint(super::CheckpointEvent),
        #[prost(message, tag="11")]
        WorkflowCompleted(super::WorkflowCompletedEvent),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AnswerBasis {
    Unspecified = 0,
    Retrieval = 1,
    Mixed = 2,
    ModelOnly = 3,
}
impl AnswerBasis {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ANSWER_BASIS_UNSPECIFIED",
            Self::Retrieval => "ANSWER_BASIS_RETRIEVAL",
            Self::Mixed => "ANSWER_BASIS_MIXED",
            Self::ModelOnly => "ANSWER_BASIS_MODEL_ONLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ANSWER_BASIS_UNSPECIFIED" => Some(Self::Unspecified),
            "ANSWER_BASIS_RETRIEVAL" => Some(Self::Retrieval),
            "ANSWER_BASIS_MIXED" => Some(Self::Mixed),
            "ANSWER_BASIS_MODEL_ONLY" => Some(Self::ModelOnly),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NoticeSeverity {
    Unspecified = 0,
    Info = 1,
    Warning = 2,
    Error = 3,
}
impl NoticeSeverity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NOTICE_SEVERITY_UNSPECIFIED",
            Self::Info => "NOTICE_SEVERITY_INFO",
            Self::Warning => "NOTICE_SEVERITY_WARNING",
            Self::Error => "NOTICE_SEVERITY_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOTICE_SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "NOTICE_SEVERITY_INFO" => Some(Self::Info),
            "NOTICE_SEVERITY_WARNING" => Some(Self::Warning),
            "NOTICE_SEVERITY_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeErrorKind {
    Unspecified = 0,
    Timeout = 1,
    Cancelled = 2,
    LlmGenerationFailed = 3,
    RetrievalFailed = 4,
    GraphFailed = 5,
    PromptAssemblyFailed = 6,
    ReformulationFailed = 7,
    Internal = 8,
    InputValidation = 9,
}
impl NodeErrorKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_ERROR_KIND_UNSPECIFIED",
            Self::Timeout => "NODE_ERROR_KIND_TIMEOUT",
            Self::Cancelled => "NODE_ERROR_KIND_CANCELLED",
            Self::LlmGenerationFailed => "NODE_ERROR_KIND_LLM_GENERATION_FAILED",
            Self::RetrievalFailed => "NODE_ERROR_KIND_RETRIEVAL_FAILED",
            Self::GraphFailed => "NODE_ERROR_KIND_GRAPH_FAILED",
            Self::PromptAssemblyFailed => "NODE_ERROR_KIND_PROMPT_ASSEMBLY_FAILED",
            Self::ReformulationFailed => "NODE_ERROR_KIND_REFORMULATION_FAILED",
            Self::Internal => "NODE_ERROR_KIND_INTERNAL",
            Self::InputValidation => "NODE_ERROR_KIND_INPUT_VALIDATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_ERROR_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_ERROR_KIND_TIMEOUT" => Some(Self::Timeout),
            "NODE_ERROR_KIND_CANCELLED" => Some(Self::Cancelled),
            "NODE_ERROR_KIND_LLM_GENERATION_FAILED" => Some(Self::LlmGenerationFailed),
            "NODE_ERROR_KIND_RETRIEVAL_FAILED" => Some(Self::RetrievalFailed),
            "NODE_ERROR_KIND_GRAPH_FAILED" => Some(Self::GraphFailed),
            "NODE_ERROR_KIND_PROMPT_ASSEMBLY_FAILED" => Some(Self::PromptAssemblyFailed),
            "NODE_ERROR_KIND_REFORMULATION_FAILED" => Some(Self::ReformulationFailed),
            "NODE_ERROR_KIND_INTERNAL" => Some(Self::Internal),
            "NODE_ERROR_KIND_INPUT_VALIDATION" => Some(Self::InputValidation),
            _ => None,
        }
    }
}
include!("lancet.v1.tonic.rs");
// @@protoc_insertion_point(module)