// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestDocumentRequest {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub chunk_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(map="string, string", tag="4")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestDocumentResponse {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub success: bool,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIngestionStatusRequest {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIngestionStatusResponse {
    #[prost(string, tag="1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub chunk_count: i32,
    #[prost(string, tag="4")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryRagRequest {
    #[prost(string, tag="1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryRagResponse {
    #[prost(string, tag="1")]
    pub answer: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub citations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryGraphRequest {
    #[prost(string, tag="1")]
    pub query: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryGraphResponse {
    #[prost(string, tag="1")]
    pub result_json: ::prost::alloc::string::String,
}
include!("lancet.v1.tonic.rs");
// @@protoc_insertion_point(module)